credentials:
  usernames:
    manager1:
      name: admin
      password: $2b$12$Q20uZzDq2aTUVgmVe2wW7OrScKRVnm3m2tbpjIxMvmkCTcHVzjHbS
      role: admin
    worker1:
      name: user
      password: $2b$12$lqy29fUbENXClf53Ga4Wre0McyZstPFuHeayu.7xK2f.Lfw1PlMH6
      role: user
cookie:
  expiry_days: 3
  key: some_signature_key
  name: some_cookie_name
preauthorized:
  emails: []
