credentials:
  usernames:
    manager1:
      name: admin
      password: pass123
      role: admin
    worker1:
      name: user
      password: pass456
      role: user
cookie:
  expiry_days: 3
  key: some_signature_key
  name: some_cookie_name
preauthorized:
  emails: []
